version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest    
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

networks:
  default:
    name: mongodb_network